import type { CuratedLick } from "./curated-licks";

// Hand-written, original R&B / neo-soul practice phrases for the right hand.
// Same conventions as curated-licks.ts: 4/4, no pickup, no ties, and the ABC mirrors
// the notes array one-for-one (rests included). These use L:1/16 so 16ths are bare
// letters, 8ths are "2", quarters "4"; each beat is beamed as its own group.
// Every phrase is a 2-bar call, a gap of at least a beat for the groove to answer,
// and a 2-bar response. soul-licks.test.ts enforces alignment and those rhythm rules.

export const SOUL_LICKS: CuratedLick[] = [
  {
    level: 1,
    kind: "lick",
    focus: "Minor pentatonic over an i–IV vamp: ghost the pickup 16ths, accent the off-beat landings.",
    practiceTempo: 66,
    lick: {
      id: "soul-01-dorian-vamp",
      genre: "rnb",
      title: "Late Night Vamp",
      bars: 4,
      tempo: 84,
      timeSignature: "4/4",
      key: "Cm",
      swing: 0.15,
      feel: "laid-back 16th groove, behind the beat",
      chords: [
        { chord: "Cm9", bar: 1, beat: 1 },
        { chord: "F13", bar: 2, beat: 1 },
        { chord: "Cm9", bar: 3, beat: 1 },
        { chord: "F13", bar: 4, beat: 1 },
      ],
      abc: `X:1\nM:4/4\nL:1/16\nK:Cm\n"Cm9" zGB2 c3e d2c2 z2B2|"F13" =A4 zGF2 z8|"Cm9" z2ec G3B c4 z2GF|"F13" ^G=A3 c2d2 A4 z4|]`,
      notes: [
        // Bar 1 (Cm9) — call: skip the downbeat, pentatonic climb, Eb on the "a" of 2
        { pitch: "rest", duration: "16n" },
        { pitch: "G4", duration: "16n", velocity: 0.35, articulation: "ghost" },
        { pitch: "Bb4", duration: "8n", velocity: 0.7, articulation: "legato" },
        { pitch: "C5", duration: "8n.", velocity: 0.8, articulation: "accent" },
        { pitch: "Eb5", duration: "16n", velocity: 0.6, articulation: "normal" },
        { pitch: "D5", duration: "8n", velocity: 0.72, articulation: "legato" },
        { pitch: "C5", duration: "8n", velocity: 0.6, articulation: "legato" },
        { pitch: "rest", duration: "8n" },
        { pitch: "Bb4", duration: "8n", velocity: 0.65, articulation: "normal" },
        // Bar 2 (F13): land the 3rd (A natural), a quick fall, then space for the response
        { pitch: "A4", duration: "4n", velocity: 0.88, articulation: "accent" },
        { pitch: "rest", duration: "16n" },
        { pitch: "G4", duration: "16n", velocity: 0.35, articulation: "ghost" },
        { pitch: "F4", duration: "8n", velocity: 0.62, articulation: "legato" },
        { pitch: "rest", duration: "2n" },
        // Bar 3 (Cm9) — response: same rhythmic cell, answered from the top
        { pitch: "rest", duration: "8n" },
        { pitch: "Eb5", duration: "16n", velocity: 0.55, articulation: "normal" },
        { pitch: "C5", duration: "16n", velocity: 0.4, articulation: "ghost" },
        { pitch: "G4", duration: "8n.", velocity: 0.75, articulation: "legato" },
        { pitch: "Bb4", duration: "16n", velocity: 0.6, articulation: "normal" },
        { pitch: "C5", duration: "4n", velocity: 0.85, articulation: "accent" },
        { pitch: "rest", duration: "8n" },
        { pitch: "G4", duration: "16n", velocity: 0.35, articulation: "ghost" },
        { pitch: "F4", duration: "16n", velocity: 0.45, articulation: "ghost" },
        // Bar 4 (F13): G# grace slides into the 3rd on the "e" of 1, 13th (D), settle on A
        { pitch: "G#4", duration: "16n", velocity: 0.4, articulation: "ghost" },
        { pitch: "A4", duration: "8n.", velocity: 0.85, articulation: "accent" },
        { pitch: "C5", duration: "8n", velocity: 0.62, articulation: "legato" },
        { pitch: "D5", duration: "8n", velocity: 0.7, articulation: "legato" },
        { pitch: "A4", duration: "4n", velocity: 0.8, articulation: "legato" },
        { pitch: "rest", duration: "4n" },
      ],
    },
  },
  {
    level: 2,
    kind: "lick",
    focus: "Soul ii–V–I: accent the off-16th E over C13, then anticipate Fmaj9 on the & of 4.",
    practiceTempo: 72,
    lick: {
      id: "soul-02-two-five-anticipation",
      genre: "rnb",
      title: "Pushed Resolution",
      bars: 4,
      tempo: 92,
      timeSignature: "4/4",
      key: "F",
      swing: 0.2,
      feel: "neo-soul 16ths, lazy swing",
      chords: [
        { chord: "Gm9", bar: 1, beat: 1 },
        { chord: "C13", bar: 2, beat: 1 },
        { chord: "Fmaj9", bar: 3, beat: 1 },
        { chord: "F6", bar: 4, beat: 1 },
      ],
      abc: `X:1\nM:4/4\nL:1/16\nK:F\n"Gm9" z2FG B3A ABd2 c4|"C13" ze3 dcA2 z4 z2A2|"Fmaj9" z4 GAc2 e3c A2G2|"F6" zDFG A8 z4|]`,
      notes: [
        // Bar 1 (Gm9) — call: 16th pickup into Bb, A (the 9th) on the "a" of 2
        { pitch: "rest", duration: "8n" },
        { pitch: "F4", duration: "16n", velocity: 0.35, articulation: "ghost" },
        { pitch: "G4", duration: "16n", velocity: 0.5, articulation: "normal" },
        { pitch: "Bb4", duration: "8n.", velocity: 0.8, articulation: "accent" },
        { pitch: "A4", duration: "16n", velocity: 0.5, articulation: "ghost" },
        { pitch: "A4", duration: "16n", velocity: 0.45, articulation: "ghost" },
        { pitch: "Bb4", duration: "16n", velocity: 0.6, articulation: "normal" },
        { pitch: "D5", duration: "8n", velocity: 0.75, articulation: "legato" },
        { pitch: "C5", duration: "4n", velocity: 0.7, articulation: "legato" },
        // Bar 2 (C13): 3rd (E) pushed onto the "e" of 1, fall to the 13th (A), space,
        // then A on the & of 4 anticipates Fmaj9's 3rd
        { pitch: "rest", duration: "16n" },
        { pitch: "E5", duration: "8n.", velocity: 0.9, articulation: "accent" },
        { pitch: "D5", duration: "16n", velocity: 0.55, articulation: "normal" },
        { pitch: "C5", duration: "16n", velocity: 0.45, articulation: "ghost" },
        { pitch: "A4", duration: "8n", velocity: 0.7, articulation: "legato" },
        { pitch: "rest", duration: "4n" },
        { pitch: "rest", duration: "8n" },
        { pitch: "A4", duration: "8n", velocity: 0.88, articulation: "accent" },
        // Bar 3 (Fmaj9) — response: beat 1 left open after the push, 9th → maj7 colours
        { pitch: "rest", duration: "4n" },
        { pitch: "G4", duration: "16n", velocity: 0.4, articulation: "ghost" },
        { pitch: "A4", duration: "16n", velocity: 0.55, articulation: "normal" },
        { pitch: "C5", duration: "8n", velocity: 0.7, articulation: "legato" },
        { pitch: "E5", duration: "8n.", velocity: 0.85, articulation: "accent" },
        { pitch: "C5", duration: "16n", velocity: 0.5, articulation: "ghost" },
        { pitch: "A4", duration: "8n", velocity: 0.65, articulation: "legato" },
        { pitch: "G4", duration: "8n", velocity: 0.6, articulation: "legato" },
        // Bar 4 (F6): 6th (D) grace figure up to the 3rd, held
        { pitch: "rest", duration: "16n" },
        { pitch: "D4", duration: "16n", velocity: 0.4, articulation: "ghost" },
        { pitch: "F4", duration: "16n", velocity: 0.55, articulation: "normal" },
        { pitch: "G4", duration: "16n", velocity: 0.6, articulation: "normal" },
        { pitch: "A4", duration: "2n", velocity: 0.85, articulation: "legato" },
        { pitch: "rest", duration: "4n" },
      ],
    },
  },
  {
    level: 3,
    kind: "lick",
    focus: "Gospel walk-down IV–iii–vi–ii–V–I: chase two chords a bar and push C6 on the & of 4.",
    practiceTempo: 60,
    lick: {
      id: "soul-03-sunday-walkdown",
      genre: "rnb",
      title: "Sunday Walk-Down",
      bars: 4,
      tempo: 76,
      timeSignature: "4/4",
      key: "C",
      swing: 0.2,
      feel: "slow gospel 16ths, church ballad",
      chords: [
        { chord: "Fmaj7", bar: 1, beat: 1 },
        { chord: "Em7", bar: 1, beat: 3 },
        { chord: "Am7", bar: 2, beat: 1 },
        { chord: "Dm9", bar: 3, beat: 1 },
        { chord: "G13", bar: 3, beat: 3 },
        { chord: "C6", bar: 4, beat: 1 },
      ],
      abc: `X:1\nM:4/4\nL:1/16\nK:C\n"Fmaj7" zAce d3c "Em7" zBGE G4|"Am7" ^GA3 c2z2 z8|"Dm9" z2EF A3c "G13" d2cA G2E2|"C6" z2GA c3A GE3 z4|]`,
      notes: [
        // Bar 1 — call. Fmaj7: 16th arpeggio up to the maj7 (E), C on the "a" of 2
        { pitch: "rest", duration: "16n" },
        { pitch: "A4", duration: "16n", velocity: 0.45, articulation: "ghost" },
        { pitch: "C5", duration: "16n", velocity: 0.55, articulation: "normal" },
        { pitch: "E5", duration: "16n", velocity: 0.7, articulation: "normal" },
        { pitch: "D5", duration: "8n.", velocity: 0.8, articulation: "accent" },
        { pitch: "C5", duration: "16n", velocity: 0.5, articulation: "ghost" },
        // Em7: the arpeggio comes back down onto its 3rd (G)
        { pitch: "rest", duration: "16n" },
        { pitch: "B4", duration: "16n", velocity: 0.5, articulation: "normal" },
        { pitch: "G4", duration: "16n", velocity: 0.45, articulation: "ghost" },
        { pitch: "E4", duration: "16n", velocity: 0.55, articulation: "normal" },
        { pitch: "G4", duration: "4n", velocity: 0.78, articulation: "legato" },
        // Bar 2 (Am7): bluesy G# grace into the root on the "e" of 1, then space
        { pitch: "G#4", duration: "16n", velocity: 0.4, articulation: "ghost" },
        { pitch: "A4", duration: "8n.", velocity: 0.88, articulation: "accent" },
        { pitch: "C5", duration: "8n", velocity: 0.65, articulation: "legato" },
        { pitch: "rest", duration: "8n" },
        { pitch: "rest", duration: "2n" },
        // Bar 3 — response. Dm9: F and A climb, C on the "a" of 2
        { pitch: "rest", duration: "8n" },
        { pitch: "E4", duration: "16n", velocity: 0.4, articulation: "ghost" },
        { pitch: "F4", duration: "16n", velocity: 0.55, articulation: "normal" },
        { pitch: "A4", duration: "8n.", velocity: 0.78, articulation: "accent" },
        { pitch: "C5", duration: "16n", velocity: 0.5, articulation: "ghost" },
        // G13: the 5th and 13th (E) walk down; E on the & of 4 anticipates C6
        { pitch: "D5", duration: "8n", velocity: 0.72, articulation: "legato" },
        { pitch: "C5", duration: "16n", velocity: 0.5, articulation: "ghost" },
        { pitch: "A4", duration: "16n", velocity: 0.55, articulation: "normal" },
        { pitch: "G4", duration: "8n", velocity: 0.65, articulation: "legato" },
        { pitch: "E4", duration: "8n", velocity: 0.85, articulation: "accent" },
        // Bar 4 (C6): the 6th (A) sings, then settle on the 3rd on the "e" of 3
        { pitch: "rest", duration: "8n" },
        { pitch: "G4", duration: "16n", velocity: 0.45, articulation: "ghost" },
        { pitch: "A4", duration: "16n", velocity: 0.6, articulation: "normal" },
        { pitch: "C5", duration: "8n.", velocity: 0.78, articulation: "legato" },
        { pitch: "A4", duration: "16n", velocity: 0.7, articulation: "accent" },
        { pitch: "G4", duration: "16n", velocity: 0.45, articulation: "ghost" },
        { pitch: "E4", duration: "8n.", velocity: 0.8, articulation: "legato" },
        { pitch: "rest", duration: "4n" },
      ],
    },
  },
];
