name = "lick-of-the-day-cron"
main = "index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 0 * * *"]  # midnight UTC daily

[[kv_namespaces]]
binding = "LICK_STORE"
id = "eb4b44c53c974515bfd6153b12da3751"
preview_id = "85b392ff625044c79b163a44d73d4fdf"
